### PR TITLE
Ticket state component

### PR DESCRIPTION
**Pull request by ninaayad**
The component will be used in the company cards and shows the state of tickets related to a specific company.

Issues:

- There is a red background on the plus sign SVG

### CODE REVIEW

**Comment by ninaayad** [comment]
Asana task: https://app.asana.com/0/1203086797794980/1203239713536436/f

**Comment by ninaayad** [comment]
Made a change on this component on the latest PR "Company card component". The only thing I changed was line 7 in the file TicketState.css, I changed the margin-bottom from 2% to 6% so if the rest looks good just change that before merging.

**Comment by MehirWolde** [comment]
Looks really good! I think it's difficult to judge these components outside of styling and such since we don't have a database or a model to test them out on.

Something im wondering is, how will we later connect these components back to know if a certain company or even has no tickets left? Since this will be rendered in a cardcomponent right, and will those also store the amount of tickets left and then send the status of the tickets to this component? This is mainly how this component will know when to change its ticketState depending on the parent component. Maybe you have already thought of this though.

The received tickets component seems to not be centered properly, its kind of centered more towards the top of the parent div and also the text seems to not be horizontally aligned with the ticket icon. Not sure how important this is but just to point out. 

Not sure on how to fix the red background on the plus sign but it probably has something to do with the SVG icon itself and its code, probably speak to Aswath about this. 

Nicely done with the different components!

**Comment by ninaayad** [comment]
I have never worked with React so I thought I would just do the template of the whole page before implementing the interactive part, but the idea is that the page view will get the ticket state information and pass it on to the card which will pass it on to the ticket state and when something changes only the ticket state should rerender so we'll probably need to set up a hook inside the TicketState component (I might be wrong but as far as I've understood that is how React works).

I'm not really sure how the ticket state will work since that is something that is company specific and not really user specific so the model needs to have an observer linked to the database and when something changes there the component rerenders.

And about the centering it works out ok when displayed on the card I think, if you have time maybe you can check out the card component to see how it looks when displayed, and if you feel like it needs adjusting I will fix it!

About the alignment, the ticket icon might be a little bit too high up now that I look at it, is that what you mean or is the alignment totally off on your computer?

**Comment by ninaayad** [comment]
Oh, okey, I will add Yash as a reviewer as well on the other PRs then! Thank you!

**Review by MehirWolde — APPROVED** [review]
Nice work, approved!

Something we might want to decide on is how to use SVGs. We can stick with the way you have done it with keeping it as just a SVG file. Or we can also make them into react component where we render the SVG code. I don't think it makes any difference in performance and usability but we should be consistent with one way since I think there is another way being used in a different PR.

**Pull request merged**
