### PR TITLE
Company card component

### PR DESCRIPTION
**Pull request by ninaayad**
The company card component is created

### CODE REVIEW

**Comment by ninaayad** [comment]
Asana task: https://app.asana.com/0/1203086797794980/1203239713536446/f

**Comment by MehirWolde** [comment]
Just after a quick look it seems really good, just some small comments:

- Regarding the tags in the cards, I dont think its a big issue if we have it like you have done. If you want to take it even further you can make a separate component that takes in the tags and then depending on if its 1 or more it will display them differently. I'm not sure how much the tags will differ or if the text will even change, maybe this will be something we see once we have all the data
- For displaying all the cards you might want to implement a card-slider or card-carousel (not sure what the exact term for it is) that will take in all the information and then render the cards in a similar structure to how it is in the figma does it where you can scroll through the cards.

I haven't been able to properly look through it but will try to look more later, good job so far though!

**Comment by ninaayad** [comment]
Thank you!

- About the tags, I guess I could do that since we use tags in the header of the page as well so we could use the component there as well, also I think we should decide on how many tags there should be at max but I guess we could decide on that once we get the information as you said. If you think it is better to implement the tags as a component I will fix that.
- Yes, you are totally right! I realized that when implementing the dashboard so I actually implemented the component there and called it CardsRow - not supersure about the name (I have not yet made a PR on it), but I did not implement the scrollfunctionality yet, I think maybe I could do the component in another PR or do you think I should include it in this one?

**Review by malinasdfghjkl — COMMENTED** [review]
Looks good for now!

**Review by malinasdfghjkl — APPROVED** [review]

**Pull request merged**
