### PR TITLE
Star button component

### PR DESCRIPTION
**Pull request by ninaayad**
A star button component is created

The star button is divided into two components one for the cards and one for the header

### CODE REVIEW

**Comment by ninaayad** [comment]
Asana task: https://app.asana.com/0/1203086797794980/1203239713536430/f

**Comment by MehirWolde** [comment]
Really nice components! I have just have some thoughts/questions:

- Which component/view will use the starbuttonheader component? I can't seem to find a similar one in the figma design, probably just me missing it
- In the css file you asked if pixels are allowed, I think that you can definitely use them. I have also done so for my components. 
- How will it work when you press the button to make it "starred" will we have to add a state later once the database has been created that we will set on each click? Is this what the onStar function prop is meant to accomplish later on?
- Maybe add the alt property to the img components in your cards to get rid of the warning messages from linters
- Maybe also use a ternary operator ( starred ? <div1/> : <div2/>) instead of && and || when you want to have an optional render based on whether starred is true or false to make it clearer in the code

If you don't feel like it's necessary to do the last parts from above you can just remove the comments and other stuff from App.tsx as you wrote and I will merge it. Good job either way, the buttons look good and the added transitions are smooth!

**Comment by ninaayad** [comment]
@MehirWolde 

- The StarButtonHeader will be used in the header component of the company information page, it is to the right of the dashboard page in the figma design, I will include a screenshot here as well.
- Ok, great! I have mostly been able to avoid using px to make the components responsive but for the star button it was the easiest way to do it.
- It will be a callback function that updates the starred attribute in the user specific model, so that it is added in the model that the user has starred the company or likewise if the user unstars the company.
- Oh I hadn't realized I had that error, will fix it directly!
- I can fix that but the thing is for the TicketState component I have 3 states so it looks ugly using the ? : operator and I thought it would be better to have the same syntax of the logic everywhere, therefore I used the && || operator here as well, but if you think it is better to just have the ? : anyways I can fix that!

**Comment by MehirWolde** [comment]
Ok I saw where the component is now, I think you might be looking at a different figma design from me. I was on the 1.0 design, but I am still a bit confused as to which one we will finally use since the one you are using has the red text above saying not to use it. Maybe we should double-check with Aswath which one will be used by the end. 

The one you were looking at: [Version 1.1](https://www.figma.com/file/CQ5Rsv64ekAMQvlk6lQ4Bi/Armada-Competition-2022?node-id=176%3A5122)
The one I was using: [Version 1.0](https://www.figma.com/file/CQ5Rsv64ekAMQvlk6lQ4Bi/Armada-Competition-2022?node-id=0%3A1)

No need to change to ternary operator if that is what fits better, works either way. Was just wondering since the linter was complaining about putting brackets to make it more clear.

Otherwise theres not much to add! The Starbuttonheader looks a bit big on my monitor but I think it will be fixed once it is put inside the final component. Remove the comments you had written about in App.tsx and its done. Good job!

**Comment by ninaayad** [comment]
Oh... I sure hope we were supposed to work on the 1.1 version, but I guess I could just fix it if that is not the case.

How do you see your warnings I don't seem to get them, I didn't get the ones for the alt tags either, is there a program I can download? Don't really know what linters are

**Comment by ninaayad** [comment]
I looked in to it and I think we were supposed to use the 1.1 design for the page. I can't really make any sense of the page of the 1.0 design, I think the 1.0 design was for the first version where we were supposed to present different events while the page of the 1.1 design presents information about the company. Because what is the meaning of presenting time and date as on the 1.0 design when the time and date is the same. Or am I just confused?

**Comment by MehirWolde** [comment]
Regarding linters, it just helps you by analyzing your code and giving you warnings and errors for stuff such as stylings and other possible issues. I would recommend downloading Eslint in your vscode. For example, for the img components, its not mandatory to include the alt property but it is still good to have in the case that an icon or image does not load for whatever reason. 

I did not use the 1.1 design because there is the big red text above that says something like "Developers do not use this".  But what you say makes more sense because the 1.1 design seems more compact and in line with what they have planned to accomplish with the current application. 

image

I think we can still merge your stuff either way since it will not conflict with other pages and we will have to sync up with the others to make sure we are working with the correct design. Good job with the components, remove the comments and other stuff from App.tsx as you have written and I will merge it.

**Comment by ninaayad** [comment]
Made a new commit now with the fixes!

**Review by MehirWolde — APPROVED** [review]
Great work, approved!

For PRs it's usually that one reviewer has to approve it before you are able to merge it into main.

**Pull request merged**
