### PR TITLE
Mehir multi step form

### PR DESCRIPTION
**Pull request by MehirWolde**
Multi step form  for registration page, need to fix 2 seperate sets of data for when we send the request to the database. Also will add a 3rd page once Vivi is done with it

### CODE REVIEW

**Comment by MehirWolde** [comment]
I apologize to anyone who has to go through this PR

**Review by mrporsev — DISMISSED** [review]
Do we really want to merge package.json and package-lock.json to the master?

**Comment by MehirWolde** [comment]
I think we can keep the changes made to the package.json and then everyone can run npm install on their own machines. This makes it easier for people to get new packages that have been installed.

**Review by yashdhanore — APPROVED** [review]
LGTM

**Pull request merged**
