### PR TITLE
Input field with regex 

### PR DESCRIPTION
**Pull request by yashdhanore**
- Checks password and email based on the regex
- Currently does not change color of the input field when the input is invalid and is not in focus

### CODE REVIEW

**Comment by MehirWolde** [comment]
I think we need to pass a value/inputValue prop and a setValue function that will set the value when an onChange event occurs. Because the value will not be handled on component level but we will handle it in the presenter/view. 

For example, when you log in you will have to send the username and the password to firebase, so we need some way of retrieving the value of the email and password input from the custom component. With a normal input we will just send the the value but now we don't have that with our custom component. 

Heres an example in javascript: https://stackoverflow.com/questions/64134105/react-how-do-i-get-the-value-of-a-custom-textinput-component

If you have any other ideas for this feel free to do that as well, good work! 😀

**Comment by DanaIso** [comment]
Nice catch @MehirWolde and great work @yashdhanore !
Resolve the issue and perhaps Mehir can merge it.

**Comment by yashdhanore** [comment]
@MehirWolde have a look now, i fixed that and also set up the login page template. Forgot to make another branch for it :P

**Comment by MehirWolde** [comment]
The page looks really good, well done! Just some small comments.

- I think you can remove the "Forgot Password" link since from what I understood we will not be able to set up a functionality for that.
- The password input field still seems to not be working properly when checking the regex and it also has a text that says "Invalid Email" when it should be "Invalid Password". I will attach an image below.

image

Except for those things it looks really good!

**Comment by yashdhanore** [comment]
Ah i forgot about that! I removed forgot password now and i don't think we need to have an invalid password prompt, so i just added invalid email to the email field.

**Review by MehirWolde — APPROVED** [review]
Really good job on the design, approved!

Just a small comment that might or might not need to be fixed, if you only click on the email input without entering anything it will have a green border as if it is a valid input even though an empty string should not be. Just something to maybe fix later on if it causes any trouble.

**Comment by yashdhanore** [comment]
Yeah! Thats kind of a minor issue. If you enter something and delete it and input field is empty then it will show invalid. I think its only an issue for the first click.

**Pull request merged**
