### PR TITLE
added functions to support logging in and registration

### PR DESCRIPTION
**Pull request by yashdhanore**
Added `LoginUser` and `RegisterUser` so one can put the necessary firebase functions for sending data to database. 

Not sure if this is the right way to do it since the functions are in View. Are they supposed to be in View?

@paklas99 you can use these once they're approved

Also, removes the comments made by Nina which i forgot to delete when merging the PR

### CODE REVIEW

**Comment by MehirWolde** [comment]
We will not create function in the view if we want to follow the MVP structure :/ but instead we will pass it as a prop from the presenter where we can set it up. I added a comment on what you can change instead but what you have done for the most part is probably what we will need. Good job!

**Comment by yashdhanore** [comment]
> We will not create function in the view if we want to follow the MVP structure :/ but instead we will pass it as a prop from the presenter where we can set it up. I added a comment on what you can change instead but what you have done for the most part is probably what we will need. Good job!

Where's the comment? So basically i have to move `LoginUser` to LoginPresenter instead of LoginView right?

**Comment by MehirWolde** [comment]
> > We will not create function in the view if we want to follow the MVP structure :/ but instead we will pass it as a prop from the presenter where we can set it up. I added a comment on what you can change instead but what you have done for the most part is probably what we will need. Good job!
> 
> Where's the comment? So basically i have to move `LoginUser` to LoginPresenter instead of LoginView right?

If you look in files changed. And yes the function will probably be in there or in another folder and then imported into the presenter (or the model) where we pass it as a prop into the view. It's been a while since I worked with MVP so im honestly not 100% sure, all I remember is that we don't create or contain any functions in the view.

**Comment by yashdhanore** [comment]
@MehirWolde Have a look now. Moved the function to presenter. I didnt move the register function since you're working on it

**Review by MehirWolde — APPROVED** [review]
Looks good, approved! We will have to check later how exactly the login and functions work, mainly with handling the response to update the model

**Pull request merged**
