### PR TITLE
User now get the points and ticket added to its collection in database

### PR DESCRIPTION
**Pull request by Adde-h**
I have merged this with the previous PR regarding superTicketLimit, in this PR users that scan the QRCode will receive the points and ticket in its collection

**Obs!** Points field has been added to the user collection database which sums the value of Supertickets (10 points) and Standardtickets (3 points), however, previously registered users do not have that field and do not start with points set to 10 for the  pre-register points

### CODE REVIEW

**Comment by MehirWolde** [comment]
@ninaayad @yashdhanore is this related to what you guys worked on yesterday? Maybe you can have a look at it so we don't have people working on the same thing

**Comment by MehirWolde** [comment]
Should we close the previous PR you made since you have merged that into here?

**Comment by Adde-h** [comment]
> Should we close the previous PR you made since you have merged that into here?

Yeah we could close the previous PR

**Review by yashdhanore — APPROVED** [review]
looks good

**Comment by MehirWolde** [comment]
@yashdhanore Should we close your other PR then since Adeel merged yours into his as well?

**Comment by yashdhanore** [comment]
@MehirWolde yes

**Comment by Adde-h** [comment]
- Now able to scan the QRCode from the website
- Updates the tickets and super tickets in the users database
- Adds the company where the ticket was scanned to visited companies' array
- Added error handling (ish) when scanning claimed tickets

**Pull request merged**
