### PR TITLE
Vivi/register-fixes

### PR DESCRIPTION
**Pull request by anderssonvivi**
Register:
- State is kept between steps (going back and forth)
- Step counter centered

Login:
- Decreased margin for login card to make consistent with register card
- Login button active condition
- Handling form submission (enter keystroke)

### CODE REVIEW

**Comment by anderssonvivi** [comment]
I will look at it at some point today!

**Comment by anderssonvivi** [comment]
Fixed:
- Gap between cards and login/register links + font sizes
- Width of login card
- Font size of input elements
- Corrected state in register to not yield errors

Did not fix:
- Register input element without border radius
- Two rows of job position names on phone

**Comment by anderssonvivi** [comment]
Fixed correct red colour, border radius, job interests in one row etc.

Yet to be fixed:
- Checkbox sizes and fixing the checkmarks to an absolute position in the boxes
- Info to users that they have to use kth email?

**Comment by yashdhanore** [comment]
Good job with the login card! Adding information about using kth email is a good idea! Also maybe we should add a prompt that if they forget the password they should get in touch with us or something? or @MehirWolde have you added that in your PR ?

**Review by yashdhanore — APPROVED** [review]

**Comment by MehirWolde** [comment]
I did not add such a thing because I don't know if anyone wants to have "email duty" during the fair days to sit and reset peoples passwords. I think people will just have to blame themselves if they forget it, unless you want to add it just to have it there and someone might look it over if they feel like it.

**Comment by yashdhanore** [comment]
We can just add that we cant help in case you forget your password so please remember it xD

**Pull request merged**
