### PR TITLE
Nina communication firebase

### PR DESCRIPTION
**Pull request by ninaayad**
The communication is now set, the performance can and should be discussed during the hackathon but I think it is fine for now. Here is what was implemented:

- You can now log in and log out, in index.tsx the logic is set with the onAuthStateChanged.
- You can communicate with the database, if something changes in the userModel the observers are notified and the database is updated. Also when logging in, the user data is loaded from firebase with the persistModel function.
- You can navigate to the home page where I have added some buttons for trying out the functionality. You can check in the console that the userModel updates correctly when clicking the buttons (I also checked that it was correctly added and removed in firebase). I implemented the buttons so that "Ninas Company" is added/removed.

Keep in mind that the whole communication can't be implemented and tested until all the views are done.

### CODE REVIEW

**Comment by ninaayad** [comment]
Just wanted to add that only the user side of the model was set up for now, the important thing is just to make sure the communication with the database works, setting up the company side (given that the communication works) should not be too hard (time consuming but not too hard). I have some ideas on how to do that but would need to discuss it.

**Review by Adde-h — APPROVED** [review]
Looks good, however, we might need syncing at the hackathon on how the database should look as I'm designing the creating and reading of tickets and you also have implemented reading the tickets from the database. Also, we need to implement that when the user is creating an account that a document with the user's uid is also created in the "users" collection (maybe you have thought of this already).

**Comment by ninaayad** [comment]
@Adde-h Yes, we definitely should, and yes, I forgot about that, I can actually just implement that now directly and then merge it or what do you think?

**Comment by Adde-h** [comment]
> @Adde-h Yes, we definitely should, and yes, I forgot about that, I can actually just implement that now directly and then merge it or what do you think?

Yeah that works if you're up for it

**Comment by DanaIso** [comment]
Is this PR ready for a merge?

**Comment by MehirWolde** [comment]
Pull down main before merging since there has been a new change to registerview.tsx

**Comment by ninaayad** [comment]
I don't know if it's only on my computer but I ran npm update to get the react-select and react-countdown and now I got a lot of errors saying Can't resolve react-select, firebase/analytics, firebase/auth, etc.

Did this after the last commit though so the last commit should be ready for merging if someone could just check it, added in RegisterView so that a document is set when a user registers.

**Pull request merged**
