### PR TITLE
Countdown component

### PR DESCRIPTION
**Pull request by malinasdfghjkl**
both components needed for the dashboard view; the countdown and ticket counter:
Asana: https://app.asana.com/0/1203086797794980/1203297887205563/f
https://app.asana.com/0/1203086797794980/1203297887205565/f

### CODE REVIEW

**Comment by MehirWolde** [comment]
Both components look really good, some small comments/questions:

- Not sure exactly how the mobile design will be but I think the components might be a bit small when switching to it, especially the title and the subtext. I assume that we will opt for having them displayed in a vertical row instead of having them laid out beside each other horizontally which allows us to have them a bit bigger. Don't think this is a pressing issue since we can always fix mobile stuff later but since you seemed to have already made it pretty responsive I wanted to add that. 
- Do you have any idea about what the arrow button will do thats on the TicketCounter in the figma design? Not sure if it will link anywhere, maybe check with Aswath
- Is the text for the countdown supposed to be that big? In the figma there seems to be some spacing between each day, hour etc and the font is smaller

Theres not really much to change, if you feel like the above comments aren't necessary changes then I can approve and merge it. Nice work!

**Comment by malinasdfghjkl** [comment]
Hi! 
1. The models have not been adjusted to mobile view, yet I didn't think it was relevant as of now.
2. Thank you! Thought the arrow was left from an outdated version, but it isn't (checked with Aswath.
3. Yes I made the font bigger as there now are only two components instead of three to span the screen.

**Comment by MehirWolde** [comment]
Ok nice, will you add the arrow or should I approve this PR and merge it?

**Comment by malinasdfghjkl** [comment]
could you merge it please and I'll add the arrow when I do the dashboard view:)

**Review by MehirWolde — APPROVED** [review]
Great job! Approved

**Pull request merged**
